# SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

"""Processors that parse raw LLM text into validated records."""

from __future__ import annotations

from abc import ABC, abstractmethod
from typing import Any, Protocol

from ..config import SafeSynthesizerParameters
from ..config.generate import ValidationParameters
from ..data_processing.record_utils import (
    ParsedRecord,
    ParsedResponse,
    check_if_records_are_ordered,
    extract_and_validate_records,
    extract_and_validate_timeseries_records,
    extract_groups_from_jsonl_string,
)
from ..llm.metadata import ModelMetadata
from ..observability import get_logger

logger = get_logger(__name__)

# Re-export the parsed-record types so existing imports of
# ``ParsedResponse`` / ``ParsedRecord`` from this module keep working.
__all__ = [
    "GroupedDataProcessor",
    "ParsedRecord",
    "ParsedResponse",
    "Processor",
    "TabularDataProcessor",
    "TimeSeriesDataProcessor",
    "create_processor",
]


class EncodeOnlyTokenizer(Protocol):
    """Tokenizer interface needed for per-record token counting."""

    def encode(self, text: str, *args: Any, **kwargs: Any) -> list[int]:
        """Return token IDs for ``text``."""


class Processor(ABC):
    """Abstract class for processing text generation results from the LLM.

    Args:
        schema: JSON schema as a dictionary.
        config: Validation parameters.
        tokenizer: Optional tokenizer for exact per-record token
            counting.  ``None`` is supported for tests and the training
            eval callback path when the tokenizer isn't readily
            available; in that case ``ParsedRecord.token_count`` is 0.
    """

    def __init__(
        self,
        schema: dict[str, Any],
        config: ValidationParameters,
        tokenizer: EncodeOnlyTokenizer | None = None,
    ):
        self.schema = schema
        self.config = config
        self._tokenizer = tokenizer
        logger.debug(
            f"Initialized processor with schema={schema}, config={config}, tokenizer_present={tokenizer is not None}"
        )

    @property
    def name(self) -> str:
        """The processor's name with spaces, for logging."""
        n = self.__class__.__name__
        return n[0] + "".join(" " + c if c.isupper() else c for c in n[1:])

    @abstractmethod
    def _process_text_generation(self, text: str) -> ParsedResponse:
        """Process the output from the LLM.

        All subclasses must implement this method. This method is responsible
        for extracting and validating records from a single string of text,
        which must be returned as a ParsedResponse object.

        Args:
            text: Text generated by the LLM.

        Returns:
            Parsed response object that contains the extracted records.
        """
        ...

    def __call__(self, prompt_number: int, text: str) -> ParsedResponse:
        """Parse a single LLM response into validated records.

        Sanitizes the text to valid UTF-8, delegates to the subclass
        ``_process_text_generation`` implementation, and tags the result
        with ``prompt_number``.

        Args:
            prompt_number: Index of the prompt within the current batch.
            text: Raw text generated by the fine-tuned model.

        Returns:
            Parsed response containing valid records, invalid records,
            and error tuples.
        """
        text = text.encode("utf-8", "ignore").decode("utf-8")

        response = self._process_text_generation(text)
        response.prompt_number = prompt_number

        return response

    @property
    def _encode(self):
        """Encode callable for the extraction helpers, or ``None``.

        Returns a ``Callable[[str], list[int]]`` that calls the
        tokenizer with ``add_special_tokens=False``, or ``None`` when no
        tokenizer was provided so the extractors can skip tokenization
        entirely.
        """
        if self._tokenizer is None:
            return None
        tokenizer = self._tokenizer
        return lambda text: tokenizer.encode(text, add_special_tokens=False)


class TabularDataProcessor(Processor):
    """Processor for standard (non-grouped, non-time-series) tabular data."""

    def _process_text_generation(self, text: str) -> ParsedResponse:
        """Extract and validate records from a flat JSONL string.

        Args:
            text: Text generated by the fine-tuned model.

        Returns:
            Parsed response with validated records and error details.
        """
        return extract_and_validate_records(text, self.schema, encode=self._encode)


class TimeSeriesDataProcessor(Processor):
    """Processor for time-series data generation tasks.

    Validates chronological ordering and timestamp intervals in
    addition to the standard schema checks.

    Args:
        schema: JSON schema as a dictionary.
        config: Validation parameters.
        time_column: Name of the timestamp column.
        interval_seconds: Expected interval between consecutive
            timestamps, or ``None`` if intervals vary.
        time_format: Timestamp format string (``strptime``), or
            ``"elapsed_seconds"`` for numeric elapsed time.
        tokenizer: Optional tokenizer for exact per-record token
            counting.

    Raises:
        ValueError: If ``time_column`` or ``time_format`` is ``None``.
    """

    def __init__(
        self,
        schema: dict[str, Any],
        config: ValidationParameters,
        time_column: str | None,
        interval_seconds: int | None,
        time_format: str | None,
        tokenizer: EncodeOnlyTokenizer | None = None,
    ):
        super().__init__(schema=schema, config=config, tokenizer=tokenizer)
        if time_column is None:
            raise ValueError(
                "time_column is required for TimeSeriesDataProcessor but was None. "
                "Ensure config.time_series.timestamp_column is set."
            )
        if time_format is None:
            raise ValueError(
                "time_format is required for TimeSeriesDataProcessor but was None. "
                "This should have been inferred during training preprocessing. "
                "Check that process_timeseries_data() was called during training and "
                "that the inferred timestamp_format was saved to the config."
            )
        self.time_column: str = time_column
        self.interval_seconds = interval_seconds
        self.time_format: str = time_format

    def _process_text_generation(self, text: str) -> ParsedResponse:
        """Extract, validate, and check temporal ordering of time-series records.

        Args:
            text: Text generated by the fine-tuned model.

        Returns:
            Parsed response with validated records and error details.
        """
        return extract_and_validate_timeseries_records(
            text,
            self.schema,
            self.time_column,
            self.interval_seconds,
            self.time_format,
            encode=self._encode,
        )


class GroupedDataProcessor(Processor):
    """Processor for grouped data generation tasks.

    Used when training examples are grouped (and optionally ordered) by
    a column.  Validates that each group has a unique ``group_by`` value
    and respects the ``order_by`` ordering.

    Args:
        schema: JSON schema as a dictionary.
        config: Validation parameters controlling tolerance for
            invalid records, non-unique group values, etc.
        bos_token: Token delimiting the beginning of a group sequence.
        eos_token: Token delimiting the end of a group sequence.
        group_by: Column name that defines groups.
        order_by: Column name to enforce ordering within a group, or
            ``None`` if ordering is not required.
        tokenizer: Optional tokenizer for exact per-record token
            counting.
    """

    def __init__(
        self,
        schema: dict[str, Any],
        config: ValidationParameters,
        bos_token: str,
        eos_token: str,
        group_by: str,
        order_by: str | None = None,
        tokenizer: EncodeOnlyTokenizer | None = None,
        first_group_without_bos: bool = False,
    ):
        super().__init__(schema=schema, config=config, tokenizer=tokenizer)
        self.group_by: list[str] = [group_by]
        self.order_by = order_by
        self.bos_token = bos_token
        self.eos_token = eos_token
        self.first_group_without_bos = first_group_without_bos

    def _process_text_generation(self, text: str) -> ParsedResponse:
        """Process the output from the fine-tuned model.

        For records to be valid, they should:
            - Be in a group that is bound by BOS and EOS tokens.
            - Respect the known JSONL schema.
            - Have a unique value for the `group_by` field(s).
            - Be ordered by the `order_by` field if specified.

        These requirements may be relaxed and automatically fixed depending on
        the settings in self.config.

        Per-record token counts (captured at extraction time) ride along
        with each :class:`ParsedRecord` through group-level
        reclassification, so aggregate token metrics stay consistent
        with the final valid/invalid partition.

        Args:
            text: Text generated by the fine-tuned model.

        Returns:
            Parsed response object that contains the extracted records.
        """
        groups = extract_groups_from_jsonl_string(
            text,
            self.bos_token,
            self.eos_token,
            first_group_without_bos=self.first_group_without_bos,
        )
        groupby_validator = "groupby"

        if len(groups) == 0 and self.config.group_by_accept_no_delineator:
            groups = [text]

        if len(groups) == 0:
            return ParsedResponse(
                records=[
                    ParsedRecord(
                        text=text,
                        error=("Group BOS and/or EOS tokens missing", groupby_validator),
                    )
                ]
            )

        all_records: list[ParsedRecord] = []
        total_tokenization_time = 0.0

        for group in groups:
            response = extract_and_validate_records(group, self.schema, encode=self._encode)
            total_tokenization_time += response.tokenization_time_sec
            group_records = response.records

            has_valid = any(r.is_valid for r in group_records)
            has_invalid = any(not r.is_valid for r in group_records)

            # Handle invalid records in the group (optionally ignore and proceed).
            if has_valid and has_invalid:
                if self.config.group_by_ignore_invalid_records:
                    group_records = [r for r in group_records if r.is_valid]
                else:
                    _reject_group_records(
                        group_records,
                        ("Invalid JSON in other groupby records", groupby_validator),
                    )

            # Handle non-unique group_by values (optionally fix by using first record's values).
            valid_parsed = _valid_parsed(group_records)
            if valid_parsed and len({tuple(record[gb] for gb in self.group_by) for record in valid_parsed}) != 1:
                if self.config.group_by_fix_non_unique_value:
                    for group_by in self.group_by:
                        for record in valid_parsed[1:]:
                            record[group_by] = valid_parsed[0][group_by]
                else:
                    _reject_group_records(
                        group_records,
                        ("Groupby value is not unique", groupby_validator),
                    )

            # Handle unordered records when order_by is set (optionally fix by sorting).
            valid_parsed = _valid_parsed(group_records)
            if (
                valid_parsed
                and self.order_by is not None
                and not check_if_records_are_ordered(valid_parsed, self.order_by)
            ):
                if self.config.group_by_fix_unordered_records:
                    # ``valid_parsed`` aliases the underlying ParsedRecord.parsed dicts,
                    # so sorting a fresh list doesn't reorder the ParsedRecord objects.
                    # Instead, sort the valid subset of group_records in-place by order_by.
                    valid_indices = [i for i, r in enumerate(group_records) if r.is_valid]
                    valid_sorted = sorted(
                        (group_records[i] for i in valid_indices),
                        key=lambda r: r.parsed[self.order_by],
                    )
                    for i, record in zip(valid_indices, valid_sorted, strict=True):
                        group_records[i] = record
                else:
                    _reject_group_records(
                        group_records,
                        ("Group not ordered", groupby_validator),
                    )

            all_records.extend(group_records)

        return ParsedResponse(
            records=all_records,
            tokenization_time_sec=total_tokenization_time,
        )


def _valid_parsed(group_records: list[ParsedRecord]) -> list[dict[str, Any]]:
    """Return the parsed dicts for each valid record in *group_records*.

    Valid records always have ``parsed`` set to a non-``None`` dict
    (invariant from [`ParsedRecord`][nemo_safe_synthesizer.data_processing.record_utils.ParsedRecord]),
    but the explicit ``is not None`` filter narrows the type for static
    analysis.
    """
    return [r.parsed for r in group_records if r.is_valid and r.parsed is not None]


def _reject_group_records(records: list[ParsedRecord], error: tuple[str, str]) -> None:
    """Reclassify every record in *records* as invalid with the given group-level error.

    The group-level error overrides any per-record error that a record
    may already carry, matching the legacy behavior where a failing
    group invalidates all its records with a single groupby reason.
    ``ParsedRecord.text`` and ``ParsedRecord.token_count`` are
    preserved, so the original regex-matched JSON string stays
    associated with the record (no ``str(dict)`` stringification) and
    per-record token counts remain correct after reclassification.
    """
    for record in records:
        record.parsed = None
        record.error = error


def create_processor(
    schema: dict[str, Any],
    metadata: ModelMetadata,
    config: SafeSynthesizerParameters,
    tokenizer: EncodeOnlyTokenizer | None = None,
) -> Processor:
    """Create the appropriate record processor for the current pipeline mode.

    Selects ``TimeSeriesDataProcessor``, ``GroupedDataProcessor``, or
    ``TabularDataProcessor`` based on the pipeline configuration.

    Args:
        schema: JSON schema describing the expected record format.
        metadata: Model metadata (prompt template, BOS/EOS tokens, etc.).
        config: Pipeline configuration determining the generation mode.
        tokenizer: Optional tokenizer for exact token counting during
            record parsing.  When ``None``, token counts are not tracked.

    Returns:
        Processor instance matching the configured generation mode.
    """
    if config.time_series.is_timeseries:
        processor = TimeSeriesDataProcessor(
            schema,
            config=config.generation.validation,
            time_column=config.time_series.timestamp_column,
            interval_seconds=config.time_series.timestamp_interval_seconds,
            time_format=config.time_series.timestamp_format,
            tokenizer=tokenizer,
        )
    elif config.data.group_training_examples_by:
        framing = metadata.response_framing
        processor = GroupedDataProcessor(
            schema,
            config=config.generation.validation,
            group_by=config.data.group_training_examples_by,
            order_by=config.data.order_training_examples_by,
            bos_token=framing.subsequent_prefix,
            eos_token=framing.suffix,
            tokenizer=tokenizer,
            first_group_without_bos=framing.first_prefix == "",
        )
    else:
        processor = TabularDataProcessor(schema, config=config.generation.validation, tokenizer=tokenizer)

    logger.info(f"Initialized the {processor.name}")
    return processor
